#!/bin/bash
set -e

echo "🌐 Remote Server Environment Demo"
echo "================================"

echo "This demo shows how to set up Nexus on a remote server."
echo ""
echo "Prerequisites:"
echo "  - Remote server (Ubuntu 22.04 recommended)"
echo "  - SSH access to the server"
echo "  - Docker installed on server"
echo ""
echo "Step 1: SSH to remote server"
echo "  ssh user@your-server-ip"
echo ""
echo "Step 2: Run install script on server"
echo "  curl -fsSL https://nexus.dev/install.sh | bash"
echo ""
echo "Step 3: Start nexusd"
echo "  nexus daemon start"
echo "  # Or use systemd for persistence"
echo ""
echo "Step 4: Configure local CLI"
echo "  export NEXUS_HOST=your-server-ip"
echo "  export NEXUS_PORT=8080"
echo ""
echo "Step 5: Create environment on remote"
echo "  nexus environment create remote-dev"
echo ""
echo "Step 6: Connect to remote environment"
echo "  nexus environment ssh remote-dev"
echo ""
echo "✅ You're now developing on a remote server!"
echo ""
echo "Useful commands:"
echo "  nexus environment list        # List remote environments"
echo "  nexus environment status ...  # Check environment status"
echo "  nexus sync status ...         # Check file sync"
