version: '3'

tasks:
  build:
    desc: Build all packages
    cmds:
      - task: build:workspace-core
      - task: build:workspace-docker
      - task: build:core
      - task: build:opencode
      # - task: build:claude
      # - task: build:cursor

  build:core:
    dir: packages/core
    cmds:
      - pnpm install
      - pnpm build

  build:opencode:
    dir: packages/opencode
    cmds:
      - pnpm install
      - pnpm build

  build:claude:
    dir: packages/claude
    cmds:
      - pnpm install
      - pnpm build

  build:cursor:
    dir: packages/cursor
    cmds:
      - pnpm install
      - pnpm build

  build:workspace-core:
    dir: packages/workspace-core
    cmds:
      - pnpm build

  build:workspace-docker:
    dir: packages/workspace-docker
    cmds:
      - pnpm build

  test:
    desc: Run all tests
    cmds:
      - task: test:core
      - task: test:opencode
      - task: test:claude
      - task: test:cursor

  test:core:
    dir: packages/core
    cmds:
      - pnpm test

  test:opencode:
    dir: packages/opencode
    cmds:
      - pnpm test

  test:claude:
    dir: packages/claude
    cmds:
      - pnpm test

  test:cursor:
    dir: packages/cursor
    cmds:
      - pnpm test

  lint:
    desc: Run all linters
    cmds:
      - task: lint:core
      - task: lint:opencode
      - task: lint:claude
      - task: lint:cursor

  lint:core:
    dir: packages/core
    cmds:
      - pnpm lint

  lint:opencode:
    dir: packages/opencode
    cmds:
      - pnpm lint

  lint:claude:
    dir: packages/claude
    cmds:
      - pnpm lint

  lint:cursor:
    dir: packages/cursor
    cmds:
      - pnpm lint

  ci:
    desc: Run CI pipeline - install, build, lint, test
    cmds:
      - pnpm install
      - task: build
      - task: lint
      - task: test

  publish:
    desc: Publish all packages to npm
    cmds:
      - task: publish:core
      - task: publish:opencode
      - task: publish:claude
      - task: publish:cursor

  publish:core:
    dir: packages/core
    cmds:
      - pnpm publish

  publish:opencode:
    dir: packages/opencode
    cmds:
      - pnpm publish

  publish:claude:
    dir: packages/claude
    cmds:
      - pnpm publish

  publish:cursor:
    dir: packages/cursor
    cmds:
      - pnpm publish

  clean:
    desc: Clean all build artifacts
    cmds:
      - rm -rf packages/core/dist
      - rm -rf packages/opencode/dist
      - rm -rf packages/claude/dist
      - rm -rf packages/cursor/dist
      - rm -rf packages/workspace-core/dist
      - rm -rf packages/workspace-docker/dist

  download-mutagen:
    desc: Download Mutagen binaries for embedding
    cmds:
      - scripts/download-mutagen.sh
