FROM debian:bookworm-slim

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        e2fsprogs \
        git \
        iproute2 \
        openssh-server \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN echo 'ListenAddress 127.0.0.1' >> /etc/ssh/sshd_config && \
    echo 'PasswordAuthentication no' >> /etc/ssh/sshd_config && \
    echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
    ssh-keygen -A

COPY nexus-agent /sbin/nexus-agent
RUN chmod 0755 /sbin/nexus-agent
