// Source: github.com/NVIDIA/openshell, commit 484f076, vendored 2026-09-21
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sandbox.proto

package computedriverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkTlsMode int32

const (
	NetworkTlsMode_NETWORK_TLS_MODE_UNSPECIFIED NetworkTlsMode = 0
	NetworkTlsMode_NETWORK_TLS_MODE_SKIP        NetworkTlsMode = 1
	// Deprecated: Marked as deprecated in sandbox.proto.
	NetworkTlsMode_NETWORK_TLS_MODE_TERMINATE NetworkTlsMode = 2
	// Deprecated: Marked as deprecated in sandbox.proto.
	NetworkTlsMode_NETWORK_TLS_MODE_PASSTHROUGH NetworkTlsMode = 3
)

// Enum value maps for NetworkTlsMode.
var (
	NetworkTlsMode_name = map[int32]string{
		0: "NETWORK_TLS_MODE_UNSPECIFIED",
		1: "NETWORK_TLS_MODE_SKIP",
		2: "NETWORK_TLS_MODE_TERMINATE",
		3: "NETWORK_TLS_MODE_PASSTHROUGH",
	}
	NetworkTlsMode_value = map[string]int32{
		"NETWORK_TLS_MODE_UNSPECIFIED": 0,
		"NETWORK_TLS_MODE_SKIP":        1,
		"NETWORK_TLS_MODE_TERMINATE":   2,
		"NETWORK_TLS_MODE_PASSTHROUGH": 3,
	}
)

func (x NetworkTlsMode) Enum() *NetworkTlsMode {
	p := new(NetworkTlsMode)
	*p = x
	return p
}

func (x NetworkTlsMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkTlsMode) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_proto_enumTypes[0].Descriptor()
}

func (NetworkTlsMode) Type() protoreflect.EnumType {
	return &file_sandbox_proto_enumTypes[0]
}

func (x NetworkTlsMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkTlsMode.Descriptor instead.
func (NetworkTlsMode) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

type NetworkEnforcementMode int32

const (
	NetworkEnforcementMode_NETWORK_ENFORCEMENT_MODE_UNSPECIFIED NetworkEnforcementMode = 0
	NetworkEnforcementMode_NETWORK_ENFORCEMENT_MODE_ENFORCE     NetworkEnforcementMode = 1
	NetworkEnforcementMode_NETWORK_ENFORCEMENT_MODE_AUDIT       NetworkEnforcementMode = 2
)

// Enum value maps for NetworkEnforcementMode.
var (
	NetworkEnforcementMode_name = map[int32]string{
		0: "NETWORK_ENFORCEMENT_MODE_UNSPECIFIED",
		1: "NETWORK_ENFORCEMENT_MODE_ENFORCE",
		2: "NETWORK_ENFORCEMENT_MODE_AUDIT",
	}
	NetworkEnforcementMode_value = map[string]int32{
		"NETWORK_ENFORCEMENT_MODE_UNSPECIFIED": 0,
		"NETWORK_ENFORCEMENT_MODE_ENFORCE":     1,
		"NETWORK_ENFORCEMENT_MODE_AUDIT":       2,
	}
)

func (x NetworkEnforcementMode) Enum() *NetworkEnforcementMode {
	p := new(NetworkEnforcementMode)
	*p = x
	return p
}

func (x NetworkEnforcementMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkEnforcementMode) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_proto_enumTypes[1].Descriptor()
}

func (NetworkEnforcementMode) Type() protoreflect.EnumType {
	return &file_sandbox_proto_enumTypes[1]
}

func (x NetworkEnforcementMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkEnforcementMode.Descriptor instead.
func (NetworkEnforcementMode) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

type NetworkAccessPreset int32

const (
	NetworkAccessPreset_NETWORK_ACCESS_PRESET_UNSPECIFIED NetworkAccessPreset = 0
	NetworkAccessPreset_NETWORK_ACCESS_PRESET_READ_ONLY   NetworkAccessPreset = 1
	NetworkAccessPreset_NETWORK_ACCESS_PRESET_READ_WRITE  NetworkAccessPreset = 2
	NetworkAccessPreset_NETWORK_ACCESS_PRESET_FULL        NetworkAccessPreset = 3
)

// Enum value maps for NetworkAccessPreset.
var (
	NetworkAccessPreset_name = map[int32]string{
		0: "NETWORK_ACCESS_PRESET_UNSPECIFIED",
		1: "NETWORK_ACCESS_PRESET_READ_ONLY",
		2: "NETWORK_ACCESS_PRESET_READ_WRITE",
		3: "NETWORK_ACCESS_PRESET_FULL",
	}
	NetworkAccessPreset_value = map[string]int32{
		"NETWORK_ACCESS_PRESET_UNSPECIFIED": 0,
		"NETWORK_ACCESS_PRESET_READ_ONLY":   1,
		"NETWORK_ACCESS_PRESET_READ_WRITE":  2,
		"NETWORK_ACCESS_PRESET_FULL":        3,
	}
)

func (x NetworkAccessPreset) Enum() *NetworkAccessPreset {
	p := new(NetworkAccessPreset)
	*p = x
	return p
}

func (x NetworkAccessPreset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkAccessPreset) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_proto_enumTypes[2].Descriptor()
}

func (NetworkAccessPreset) Type() protoreflect.EnumType {
	return &file_sandbox_proto_enumTypes[2]
}

func (x NetworkAccessPreset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkAccessPreset.Descriptor instead.
func (NetworkAccessPreset) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{2}
}

type SettingScope int32

const (
	SettingScope_SETTING_SCOPE_UNSPECIFIED SettingScope = 0
	SettingScope_SETTING_SCOPE_SANDBOX     SettingScope = 1
	SettingScope_SETTING_SCOPE_GLOBAL      SettingScope = 2
)

// Enum value maps for SettingScope.
var (
	SettingScope_name = map[int32]string{
		0: "SETTING_SCOPE_UNSPECIFIED",
		1: "SETTING_SCOPE_SANDBOX",
		2: "SETTING_SCOPE_GLOBAL",
	}
	SettingScope_value = map[string]int32{
		"SETTING_SCOPE_UNSPECIFIED": 0,
		"SETTING_SCOPE_SANDBOX":     1,
		"SETTING_SCOPE_GLOBAL":      2,
	}
)

func (x SettingScope) Enum() *SettingScope {
	p := new(SettingScope)
	*p = x
	return p
}

func (x SettingScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SettingScope) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_proto_enumTypes[3].Descriptor()
}

func (SettingScope) Type() protoreflect.EnumType {
	return &file_sandbox_proto_enumTypes[3]
}

func (x SettingScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SettingScope.Descriptor instead.
func (SettingScope) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{3}
}

type PolicySource int32

const (
	PolicySource_POLICY_SOURCE_UNSPECIFIED PolicySource = 0
	PolicySource_POLICY_SOURCE_SANDBOX     PolicySource = 1
	PolicySource_POLICY_SOURCE_GLOBAL      PolicySource = 2
)

// Enum value maps for PolicySource.
var (
	PolicySource_name = map[int32]string{
		0: "POLICY_SOURCE_UNSPECIFIED",
		1: "POLICY_SOURCE_SANDBOX",
		2: "POLICY_SOURCE_GLOBAL",
	}
	PolicySource_value = map[string]int32{
		"POLICY_SOURCE_UNSPECIFIED": 0,
		"POLICY_SOURCE_SANDBOX":     1,
		"POLICY_SOURCE_GLOBAL":      2,
	}
)

func (x PolicySource) Enum() *PolicySource {
	p := new(PolicySource)
	*p = x
	return p
}

func (x PolicySource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicySource) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_proto_enumTypes[4].Descriptor()
}

func (PolicySource) Type() protoreflect.EnumType {
	return &file_sandbox_proto_enumTypes[4]
}

func (x PolicySource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicySource.Descriptor instead.
func (PolicySource) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{4}
}

type SandboxPolicy struct {
	state              protoimpl.MessageState              `protogen:"open.v1"`
	Version            uint32                              `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Filesystem         *FilesystemPolicy                   `protobuf:"bytes,2,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	Landlock           *LandlockPolicy                     `protobuf:"bytes,3,opt,name=landlock,proto3" json:"landlock,omitempty"`
	Process            *ProcessPolicy                      `protobuf:"bytes,4,opt,name=process,proto3" json:"process,omitempty"`
	NetworkPolicies    map[string]*NetworkPolicyRule       `protobuf:"bytes,5,rep,name=network_policies,json=networkPolicies,proto3" json:"network_policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NetworkMiddlewares map[string]*NetworkMiddlewareConfig `protobuf:"bytes,6,rep,name=network_middlewares,json=networkMiddlewares,proto3" json:"network_middlewares,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SandboxPolicy) Reset() {
	*x = SandboxPolicy{}
	mi := &file_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxPolicy) ProtoMessage() {}

func (x *SandboxPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxPolicy.ProtoReflect.Descriptor instead.
func (*SandboxPolicy) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxPolicy) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SandboxPolicy) GetFilesystem() *FilesystemPolicy {
	if x != nil {
		return x.Filesystem
	}
	return nil
}

func (x *SandboxPolicy) GetLandlock() *LandlockPolicy {
	if x != nil {
		return x.Landlock
	}
	return nil
}

func (x *SandboxPolicy) GetProcess() *ProcessPolicy {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *SandboxPolicy) GetNetworkPolicies() map[string]*NetworkPolicyRule {
	if x != nil {
		return x.NetworkPolicies
	}
	return nil
}

func (x *SandboxPolicy) GetNetworkMiddlewares() map[string]*NetworkMiddlewareConfig {
	if x != nil {
		return x.NetworkMiddlewares
	}
	return nil
}

type FilesystemPolicy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeWorkdir bool                   `protobuf:"varint,1,opt,name=include_workdir,json=includeWorkdir,proto3" json:"include_workdir,omitempty"`
	ReadOnly       []string               `protobuf:"bytes,2,rep,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	ReadWrite      []string               `protobuf:"bytes,3,rep,name=read_write,json=readWrite,proto3" json:"read_write,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FilesystemPolicy) Reset() {
	*x = FilesystemPolicy{}
	mi := &file_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemPolicy) ProtoMessage() {}

func (x *FilesystemPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemPolicy.ProtoReflect.Descriptor instead.
func (*FilesystemPolicy) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *FilesystemPolicy) GetIncludeWorkdir() bool {
	if x != nil {
		return x.IncludeWorkdir
	}
	return false
}

func (x *FilesystemPolicy) GetReadOnly() []string {
	if x != nil {
		return x.ReadOnly
	}
	return nil
}

func (x *FilesystemPolicy) GetReadWrite() []string {
	if x != nil {
		return x.ReadWrite
	}
	return nil
}

type LandlockPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compatibility string                 `protobuf:"bytes,1,opt,name=compatibility,proto3" json:"compatibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandlockPolicy) Reset() {
	*x = LandlockPolicy{}
	mi := &file_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandlockPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlockPolicy) ProtoMessage() {}

func (x *LandlockPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlockPolicy.ProtoReflect.Descriptor instead.
func (*LandlockPolicy) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *LandlockPolicy) GetCompatibility() string {
	if x != nil {
		return x.Compatibility
	}
	return ""
}

type ProcessPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunAsUser     string                 `protobuf:"bytes,1,opt,name=run_as_user,json=runAsUser,proto3" json:"run_as_user,omitempty"`
	RunAsGroup    string                 `protobuf:"bytes,2,opt,name=run_as_group,json=runAsGroup,proto3" json:"run_as_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPolicy) Reset() {
	*x = ProcessPolicy{}
	mi := &file_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPolicy) ProtoMessage() {}

func (x *ProcessPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPolicy.ProtoReflect.Descriptor instead.
func (*ProcessPolicy) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessPolicy) GetRunAsUser() string {
	if x != nil {
		return x.RunAsUser
	}
	return ""
}

func (x *ProcessPolicy) GetRunAsGroup() string {
	if x != nil {
		return x.RunAsGroup
	}
	return ""
}

type NetworkPolicyRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoints     []*NetworkEndpoint     `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Binaries      []*NetworkBinary       `protobuf:"bytes,3,rep,name=binaries,proto3" json:"binaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyRule) Reset() {
	*x = NetworkPolicyRule{}
	mi := &file_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyRule) ProtoMessage() {}

func (x *NetworkPolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyRule.ProtoReflect.Descriptor instead.
func (*NetworkPolicyRule) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkPolicyRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkPolicyRule) GetEndpoints() []*NetworkEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NetworkPolicyRule) GetBinaries() []*NetworkBinary {
	if x != nil {
		return x.Binaries
	}
	return nil
}

type NetworkMiddlewareConfig struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Name          string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Middleware    string                      `protobuf:"bytes,2,opt,name=middleware,proto3" json:"middleware,omitempty"`
	Config        *structpb.Struct            `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	OnError       string                      `protobuf:"bytes,4,opt,name=on_error,json=onError,proto3" json:"on_error,omitempty"`
	Endpoints     *MiddlewareEndpointSelector `protobuf:"bytes,5,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	Order         int32                       `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMiddlewareConfig) Reset() {
	*x = NetworkMiddlewareConfig{}
	mi := &file_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMiddlewareConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMiddlewareConfig) ProtoMessage() {}

func (x *NetworkMiddlewareConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMiddlewareConfig.ProtoReflect.Descriptor instead.
func (*NetworkMiddlewareConfig) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkMiddlewareConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkMiddlewareConfig) GetMiddleware() string {
	if x != nil {
		return x.Middleware
	}
	return ""
}

func (x *NetworkMiddlewareConfig) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *NetworkMiddlewareConfig) GetOnError() string {
	if x != nil {
		return x.OnError
	}
	return ""
}

func (x *NetworkMiddlewareConfig) GetEndpoints() *MiddlewareEndpointSelector {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NetworkMiddlewareConfig) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type MiddlewareEndpointSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Include       []string               `protobuf:"bytes,1,rep,name=include,proto3" json:"include,omitempty"`
	Exclude       []string               `protobuf:"bytes,2,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiddlewareEndpointSelector) Reset() {
	*x = MiddlewareEndpointSelector{}
	mi := &file_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareEndpointSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareEndpointSelector) ProtoMessage() {}

func (x *MiddlewareEndpointSelector) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareEndpointSelector.ProtoReflect.Descriptor instead.
func (*MiddlewareEndpointSelector) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *MiddlewareEndpointSelector) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *MiddlewareEndpointSelector) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type NetworkCredentialBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkCredentialBinding) Reset() {
	*x = NetworkCredentialBinding{}
	mi := &file_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkCredentialBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkCredentialBinding) ProtoMessage() {}

func (x *NetworkCredentialBinding) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkCredentialBinding.ProtoReflect.Descriptor instead.
func (*NetworkCredentialBinding) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkCredentialBinding) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type NetworkEndpoint struct {
	state                        protoimpl.MessageState       `protogen:"open.v1"`
	Host                         string                       `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                         uint32                       `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol                     string                       `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Tls                          NetworkTlsMode               `protobuf:"varint,4,opt,name=tls,proto3,enum=openshell.sandbox.v1.NetworkTlsMode" json:"tls,omitempty"`
	Enforcement                  NetworkEnforcementMode       `protobuf:"varint,5,opt,name=enforcement,proto3,enum=openshell.sandbox.v1.NetworkEnforcementMode" json:"enforcement,omitempty"`
	Access                       NetworkAccessPreset          `protobuf:"varint,6,opt,name=access,proto3,enum=openshell.sandbox.v1.NetworkAccessPreset" json:"access,omitempty"`
	Rules                        []*L7Rule                    `protobuf:"bytes,7,rep,name=rules,proto3" json:"rules,omitempty"`
	AllowedIps                   []string                     `protobuf:"bytes,8,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Ports                        []uint32                     `protobuf:"varint,9,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	DenyRules                    []*L7DenyRule                `protobuf:"bytes,10,rep,name=deny_rules,json=denyRules,proto3" json:"deny_rules,omitempty"`
	AllowEncodedSlash            bool                         `protobuf:"varint,11,opt,name=allow_encoded_slash,json=allowEncodedSlash,proto3" json:"allow_encoded_slash,omitempty"`
	PersistedQueries             string                       `protobuf:"bytes,12,opt,name=persisted_queries,json=persistedQueries,proto3" json:"persisted_queries,omitempty"`
	GraphqlPersistedQueries      map[string]*GraphqlOperation `protobuf:"bytes,13,rep,name=graphql_persisted_queries,json=graphqlPersistedQueries,proto3" json:"graphql_persisted_queries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GraphqlMaxBodyBytes          uint32                       `protobuf:"varint,14,opt,name=graphql_max_body_bytes,json=graphqlMaxBodyBytes,proto3" json:"graphql_max_body_bytes,omitempty"`
	Path                         string                       `protobuf:"bytes,15,opt,name=path,proto3" json:"path,omitempty"`
	WebsocketCredentialRewrite   bool                         `protobuf:"varint,16,opt,name=websocket_credential_rewrite,json=websocketCredentialRewrite,proto3" json:"websocket_credential_rewrite,omitempty"`
	RequestBodyCredentialRewrite bool                         `protobuf:"varint,17,opt,name=request_body_credential_rewrite,json=requestBodyCredentialRewrite,proto3" json:"request_body_credential_rewrite,omitempty"`
	AdvisorProposed              bool                         `protobuf:"varint,18,opt,name=advisor_proposed,json=advisorProposed,proto3" json:"advisor_proposed,omitempty"`
	CredentialSigning            string                       `protobuf:"bytes,19,opt,name=credential_signing,json=credentialSigning,proto3" json:"credential_signing,omitempty"`
	SigningService               string                       `protobuf:"bytes,20,opt,name=signing_service,json=signingService,proto3" json:"signing_service,omitempty"`
	SigningRegion                string                       `protobuf:"bytes,21,opt,name=signing_region,json=signingRegion,proto3" json:"signing_region,omitempty"`
	JsonRpcMaxBodyBytes          uint32                       `protobuf:"varint,22,opt,name=json_rpc_max_body_bytes,json=jsonRpcMaxBodyBytes,proto3" json:"json_rpc_max_body_bytes,omitempty"`
	Mcp                          *McpOptions                  `protobuf:"bytes,23,opt,name=mcp,proto3" json:"mcp,omitempty"`
	CredentialBinding            *NetworkCredentialBinding    `protobuf:"bytes,24,opt,name=credential_binding,json=credentialBinding,proto3" json:"credential_binding,omitempty"`
	AllowUninspectedCredentials  bool                         `protobuf:"varint,25,opt,name=allow_uninspected_credentials,json=allowUninspectedCredentials,proto3" json:"allow_uninspected_credentials,omitempty"`
	ProviderCredentialed         bool                         `protobuf:"varint,26,opt,name=provider_credentialed,json=providerCredentialed,proto3" json:"provider_credentialed,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *NetworkEndpoint) Reset() {
	*x = NetworkEndpoint{}
	mi := &file_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndpoint) ProtoMessage() {}

func (x *NetworkEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndpoint.ProtoReflect.Descriptor instead.
func (*NetworkEndpoint) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkEndpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NetworkEndpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NetworkEndpoint) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkEndpoint) GetTls() NetworkTlsMode {
	if x != nil {
		return x.Tls
	}
	return NetworkTlsMode_NETWORK_TLS_MODE_UNSPECIFIED
}

func (x *NetworkEndpoint) GetEnforcement() NetworkEnforcementMode {
	if x != nil {
		return x.Enforcement
	}
	return NetworkEnforcementMode_NETWORK_ENFORCEMENT_MODE_UNSPECIFIED
}

func (x *NetworkEndpoint) GetAccess() NetworkAccessPreset {
	if x != nil {
		return x.Access
	}
	return NetworkAccessPreset_NETWORK_ACCESS_PRESET_UNSPECIFIED
}

func (x *NetworkEndpoint) GetRules() []*L7Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *NetworkEndpoint) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *NetworkEndpoint) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *NetworkEndpoint) GetDenyRules() []*L7DenyRule {
	if x != nil {
		return x.DenyRules
	}
	return nil
}

func (x *NetworkEndpoint) GetAllowEncodedSlash() bool {
	if x != nil {
		return x.AllowEncodedSlash
	}
	return false
}

func (x *NetworkEndpoint) GetPersistedQueries() string {
	if x != nil {
		return x.PersistedQueries
	}
	return ""
}

func (x *NetworkEndpoint) GetGraphqlPersistedQueries() map[string]*GraphqlOperation {
	if x != nil {
		return x.GraphqlPersistedQueries
	}
	return nil
}

func (x *NetworkEndpoint) GetGraphqlMaxBodyBytes() uint32 {
	if x != nil {
		return x.GraphqlMaxBodyBytes
	}
	return 0
}

func (x *NetworkEndpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NetworkEndpoint) GetWebsocketCredentialRewrite() bool {
	if x != nil {
		return x.WebsocketCredentialRewrite
	}
	return false
}

func (x *NetworkEndpoint) GetRequestBodyCredentialRewrite() bool {
	if x != nil {
		return x.RequestBodyCredentialRewrite
	}
	return false
}

func (x *NetworkEndpoint) GetAdvisorProposed() bool {
	if x != nil {
		return x.AdvisorProposed
	}
	return false
}

func (x *NetworkEndpoint) GetCredentialSigning() string {
	if x != nil {
		return x.CredentialSigning
	}
	return ""
}

func (x *NetworkEndpoint) GetSigningService() string {
	if x != nil {
		return x.SigningService
	}
	return ""
}

func (x *NetworkEndpoint) GetSigningRegion() string {
	if x != nil {
		return x.SigningRegion
	}
	return ""
}

func (x *NetworkEndpoint) GetJsonRpcMaxBodyBytes() uint32 {
	if x != nil {
		return x.JsonRpcMaxBodyBytes
	}
	return 0
}

func (x *NetworkEndpoint) GetMcp() *McpOptions {
	if x != nil {
		return x.Mcp
	}
	return nil
}

func (x *NetworkEndpoint) GetCredentialBinding() *NetworkCredentialBinding {
	if x != nil {
		return x.CredentialBinding
	}
	return nil
}

func (x *NetworkEndpoint) GetAllowUninspectedCredentials() bool {
	if x != nil {
		return x.AllowUninspectedCredentials
	}
	return false
}

func (x *NetworkEndpoint) GetProviderCredentialed() bool {
	if x != nil {
		return x.ProviderCredentialed
	}
	return false
}

type McpOptions struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	StrictToolNames         *bool                  `protobuf:"varint,1,opt,name=strict_tool_names,json=strictToolNames,proto3,oneof" json:"strict_tool_names,omitempty"`
	AllowAllKnownMcpMethods *bool                  `protobuf:"varint,2,opt,name=allow_all_known_mcp_methods,json=allowAllKnownMcpMethods,proto3,oneof" json:"allow_all_known_mcp_methods,omitempty"`
	Versions                []string               `protobuf:"bytes,3,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *McpOptions) Reset() {
	*x = McpOptions{}
	mi := &file_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpOptions) ProtoMessage() {}

func (x *McpOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpOptions.ProtoReflect.Descriptor instead.
func (*McpOptions) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *McpOptions) GetStrictToolNames() bool {
	if x != nil && x.StrictToolNames != nil {
		return *x.StrictToolNames
	}
	return false
}

func (x *McpOptions) GetAllowAllKnownMcpMethods() bool {
	if x != nil && x.AllowAllKnownMcpMethods != nil {
		return *x.AllowAllKnownMcpMethods
	}
	return false
}

func (x *McpOptions) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

type GraphqlOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationType string                 `protobuf:"bytes,1,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	OperationName string                 `protobuf:"bytes,2,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	Fields        []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphqlOperation) Reset() {
	*x = GraphqlOperation{}
	mi := &file_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphqlOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlOperation) ProtoMessage() {}

func (x *GraphqlOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlOperation.ProtoReflect.Descriptor instead.
func (*GraphqlOperation) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *GraphqlOperation) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *GraphqlOperation) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *GraphqlOperation) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type L7DenyRule struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Method        string                     `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                     `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Command       string                     `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Query         map[string]*L7QueryMatcher `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OperationType string                     `protobuf:"bytes,5,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	OperationName string                     `protobuf:"bytes,6,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	Fields        []string                   `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty"`
	Params        map[string]*L7QueryMatcher `protobuf:"bytes,9,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7DenyRule) Reset() {
	*x = L7DenyRule{}
	mi := &file_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7DenyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7DenyRule) ProtoMessage() {}

func (x *L7DenyRule) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7DenyRule.ProtoReflect.Descriptor instead.
func (*L7DenyRule) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{11}
}

func (x *L7DenyRule) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *L7DenyRule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *L7DenyRule) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *L7DenyRule) GetQuery() map[string]*L7QueryMatcher {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *L7DenyRule) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *L7DenyRule) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *L7DenyRule) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *L7DenyRule) GetParams() map[string]*L7QueryMatcher {
	if x != nil {
		return x.Params
	}
	return nil
}

type L7Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         *L7Allow               `protobuf:"bytes,1,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7Rule) Reset() {
	*x = L7Rule{}
	mi := &file_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7Rule) ProtoMessage() {}

func (x *L7Rule) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7Rule.ProtoReflect.Descriptor instead.
func (*L7Rule) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{12}
}

func (x *L7Rule) GetAllow() *L7Allow {
	if x != nil {
		return x.Allow
	}
	return nil
}

type L7Allow struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Method        string                     `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                     `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Command       string                     `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Query         map[string]*L7QueryMatcher `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OperationType string                     `protobuf:"bytes,5,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	OperationName string                     `protobuf:"bytes,6,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	Fields        []string                   `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty"`
	Params        map[string]*L7QueryMatcher `protobuf:"bytes,9,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7Allow) Reset() {
	*x = L7Allow{}
	mi := &file_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7Allow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7Allow) ProtoMessage() {}

func (x *L7Allow) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7Allow.ProtoReflect.Descriptor instead.
func (*L7Allow) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *L7Allow) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *L7Allow) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *L7Allow) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *L7Allow) GetQuery() map[string]*L7QueryMatcher {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *L7Allow) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *L7Allow) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *L7Allow) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *L7Allow) GetParams() map[string]*L7QueryMatcher {
	if x != nil {
		return x.Params
	}
	return nil
}

type L7QueryMatcher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Glob          string                 `protobuf:"bytes,1,opt,name=glob,proto3" json:"glob,omitempty"`
	Any           []string               `protobuf:"bytes,2,rep,name=any,proto3" json:"any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7QueryMatcher) Reset() {
	*x = L7QueryMatcher{}
	mi := &file_sandbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7QueryMatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7QueryMatcher) ProtoMessage() {}

func (x *L7QueryMatcher) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7QueryMatcher.ProtoReflect.Descriptor instead.
func (*L7QueryMatcher) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{14}
}

func (x *L7QueryMatcher) GetGlob() string {
	if x != nil {
		return x.Glob
	}
	return ""
}

func (x *L7QueryMatcher) GetAny() []string {
	if x != nil {
		return x.Any
	}
	return nil
}

type NetworkBinary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkBinary) Reset() {
	*x = NetworkBinary{}
	mi := &file_sandbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkBinary) ProtoMessage() {}

func (x *NetworkBinary) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkBinary.ProtoReflect.Descriptor instead.
func (*NetworkBinary) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{15}
}

func (x *NetworkBinary) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetSandboxConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceScope *WorkspaceSelector     `protobuf:"bytes,3,opt,name=workspace_scope,json=workspaceScope,proto3" json:"workspace_scope,omitempty"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSandboxConfigRequest) Reset() {
	*x = GetSandboxConfigRequest{}
	mi := &file_sandbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxConfigRequest) ProtoMessage() {}

func (x *GetSandboxConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxConfigRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxConfigRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{16}
}

func (x *GetSandboxConfigRequest) GetWorkspaceScope() *WorkspaceSelector {
	if x != nil {
		return x.WorkspaceScope
	}
	return nil
}

func (x *GetSandboxConfigRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetGatewayConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayConfigRequest) Reset() {
	*x = GetGatewayConfigRequest{}
	mi := &file_sandbox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayConfigRequest) ProtoMessage() {}

func (x *GetGatewayConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayConfigRequest.ProtoReflect.Descriptor instead.
func (*GetGatewayConfigRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{17}
}

type GetGatewayConfigResponse struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Settings         map[string]*SettingValue `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SettingsRevision uint64                   `protobuf:"varint,2,opt,name=settings_revision,json=settingsRevision,proto3" json:"settings_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetGatewayConfigResponse) Reset() {
	*x = GetGatewayConfigResponse{}
	mi := &file_sandbox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayConfigResponse) ProtoMessage() {}

func (x *GetGatewayConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayConfigResponse.ProtoReflect.Descriptor instead.
func (*GetGatewayConfigResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{18}
}

func (x *GetGatewayConfigResponse) GetSettings() map[string]*SettingValue {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetGatewayConfigResponse) GetSettingsRevision() uint64 {
	if x != nil {
		return x.SettingsRevision
	}
	return 0
}

type SettingValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*SettingValue_StringValue
	//	*SettingValue_BoolValue
	//	*SettingValue_IntValue
	//	*SettingValue_BytesValue
	Value         isSettingValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingValue) Reset() {
	*x = SettingValue{}
	mi := &file_sandbox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingValue) ProtoMessage() {}

func (x *SettingValue) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingValue.ProtoReflect.Descriptor instead.
func (*SettingValue) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{19}
}

func (x *SettingValue) GetValue() isSettingValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SettingValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*SettingValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *SettingValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*SettingValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *SettingValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*SettingValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *SettingValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*SettingValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isSettingValue_Value interface {
	isSettingValue_Value()
}

type SettingValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type SettingValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type SettingValue_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type SettingValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,4,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*SettingValue_StringValue) isSettingValue_Value() {}

func (*SettingValue_BoolValue) isSettingValue_Value() {}

func (*SettingValue_IntValue) isSettingValue_Value() {}

func (*SettingValue_BytesValue) isSettingValue_Value() {}

type EffectiveSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *SettingValue          `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Scope         SettingScope           `protobuf:"varint,2,opt,name=scope,proto3,enum=openshell.sandbox.v1.SettingScope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectiveSetting) Reset() {
	*x = EffectiveSetting{}
	mi := &file_sandbox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectiveSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectiveSetting) ProtoMessage() {}

func (x *EffectiveSetting) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectiveSetting.ProtoReflect.Descriptor instead.
func (*EffectiveSetting) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{20}
}

func (x *EffectiveSetting) GetValue() *SettingValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *EffectiveSetting) GetScope() SettingScope {
	if x != nil {
		return x.Scope
	}
	return SettingScope_SETTING_SCOPE_UNSPECIFIED
}

type GetSandboxConfigResponse struct {
	state                          protoimpl.MessageState         `protogen:"open.v1"`
	Policy                         *SandboxPolicy                 `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Version                        uint32                         `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	PolicyHash                     string                         `protobuf:"bytes,3,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
	Settings                       map[string]*EffectiveSetting   `protobuf:"bytes,4,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfigRevision                 uint64                         `protobuf:"varint,5,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	PolicySource                   PolicySource                   `protobuf:"varint,6,opt,name=policy_source,json=policySource,proto3,enum=openshell.sandbox.v1.PolicySource" json:"policy_source,omitempty"`
	GlobalPolicyVersion            uint32                         `protobuf:"varint,7,opt,name=global_policy_version,json=globalPolicyVersion,proto3" json:"global_policy_version,omitempty"`
	ProviderEnvRevision            uint64                         `protobuf:"varint,8,opt,name=provider_env_revision,json=providerEnvRevision,proto3" json:"provider_env_revision,omitempty"`
	SupervisorMiddlewareServices   []*SupervisorMiddlewareService `protobuf:"bytes,9,rep,name=supervisor_middleware_services,json=supervisorMiddlewareServices,proto3" json:"supervisor_middleware_services,omitempty"`
	Workspace                      string                         `protobuf:"bytes,10,opt,name=workspace,proto3" json:"workspace,omitempty"`
	PolicyValidationFailureMode    string                         `protobuf:"bytes,11,opt,name=policy_validation_failure_mode,json=policyValidationFailureMode,proto3" json:"policy_validation_failure_mode,omitempty"`
	ExtensionAuthenticationEnabled bool                           `protobuf:"varint,12,opt,name=extension_authentication_enabled,json=extensionAuthenticationEnabled,proto3" json:"extension_authentication_enabled,omitempty"`
	ProviderAttachmentEpoch        string                         `protobuf:"bytes,14,opt,name=provider_attachment_epoch,json=providerAttachmentEpoch,proto3" json:"provider_attachment_epoch,omitempty"`
	ConfigurationAdmitted          bool                           `protobuf:"varint,13,opt,name=configuration_admitted,json=configurationAdmitted,proto3" json:"configuration_admitted,omitempty"`
	ConfigurationError             string                         `protobuf:"bytes,16,opt,name=configuration_error,json=configurationError,proto3" json:"configuration_error,omitempty"`
	ConfigurationInstanceId        string                         `protobuf:"bytes,15,opt,name=configuration_instance_id,json=configurationInstanceId,proto3" json:"configuration_instance_id,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GetSandboxConfigResponse) Reset() {
	*x = GetSandboxConfigResponse{}
	mi := &file_sandbox_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxConfigResponse) ProtoMessage() {}

func (x *GetSandboxConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxConfigResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxConfigResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{21}
}

func (x *GetSandboxConfigResponse) GetPolicy() *SandboxPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *GetSandboxConfigResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetSandboxConfigResponse) GetPolicyHash() string {
	if x != nil {
		return x.PolicyHash
	}
	return ""
}

func (x *GetSandboxConfigResponse) GetSettings() map[string]*EffectiveSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetSandboxConfigResponse) GetConfigRevision() uint64 {
	if x != nil {
		return x.ConfigRevision
	}
	return 0
}

func (x *GetSandboxConfigResponse) GetPolicySource() PolicySource {
	if x != nil {
		return x.PolicySource
	}
	return PolicySource_POLICY_SOURCE_UNSPECIFIED
}

func (x *GetSandboxConfigResponse) GetGlobalPolicyVersion() uint32 {
	if x != nil {
		return x.GlobalPolicyVersion
	}
	return 0
}

func (x *GetSandboxConfigResponse) GetProviderEnvRevision() uint64 {
	if x != nil {
		return x.ProviderEnvRevision
	}
	return 0
}

func (x *GetSandboxConfigResponse) GetSupervisorMiddlewareServices() []*SupervisorMiddlewareService {
	if x != nil {
		return x.SupervisorMiddlewareServices
	}
	return nil
}

func (x *GetSandboxConfigResponse) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *GetSandboxConfigResponse) GetPolicyValidationFailureMode() string {
	if x != nil {
		return x.PolicyValidationFailureMode
	}
	return ""
}

func (x *GetSandboxConfigResponse) GetExtensionAuthenticationEnabled() bool {
	if x != nil {
		return x.ExtensionAuthenticationEnabled
	}
	return false
}

func (x *GetSandboxConfigResponse) GetProviderAttachmentEpoch() string {
	if x != nil {
		return x.ProviderAttachmentEpoch
	}
	return ""
}

func (x *GetSandboxConfigResponse) GetConfigurationAdmitted() bool {
	if x != nil {
		return x.ConfigurationAdmitted
	}
	return false
}

func (x *GetSandboxConfigResponse) GetConfigurationError() string {
	if x != nil {
		return x.ConfigurationError
	}
	return ""
}

func (x *GetSandboxConfigResponse) GetConfigurationInstanceId() string {
	if x != nil {
		return x.ConfigurationInstanceId
	}
	return ""
}

type SupervisorMiddlewareService struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GrpcEndpoint           string                 `protobuf:"bytes,2,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	MaxPayloadBytes        uint64                 `protobuf:"varint,3,opt,name=max_payload_bytes,json=maxPayloadBytes,proto3" json:"max_payload_bytes,omitempty"`
	RequestTimeout         *durationpb.Duration   `protobuf:"bytes,104,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	TlsCaCertPem           []byte                 `protobuf:"bytes,5,opt,name=tls_ca_cert_pem,json=tlsCaCertPem,proto3" json:"tls_ca_cert_pem,omitempty"`
	Audience               string                 `protobuf:"bytes,6,opt,name=audience,proto3" json:"audience,omitempty"`
	AllowInsecureTransport bool                   `protobuf:"varint,7,opt,name=allow_insecure_transport,json=allowInsecureTransport,proto3" json:"allow_insecure_transport,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SupervisorMiddlewareService) Reset() {
	*x = SupervisorMiddlewareService{}
	mi := &file_sandbox_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisorMiddlewareService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisorMiddlewareService) ProtoMessage() {}

func (x *SupervisorMiddlewareService) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisorMiddlewareService.ProtoReflect.Descriptor instead.
func (*SupervisorMiddlewareService) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{22}
}

func (x *SupervisorMiddlewareService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SupervisorMiddlewareService) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

func (x *SupervisorMiddlewareService) GetMaxPayloadBytes() uint64 {
	if x != nil {
		return x.MaxPayloadBytes
	}
	return 0
}

func (x *SupervisorMiddlewareService) GetRequestTimeout() *durationpb.Duration {
	if x != nil {
		return x.RequestTimeout
	}
	return nil
}

func (x *SupervisorMiddlewareService) GetTlsCaCertPem() []byte {
	if x != nil {
		return x.TlsCaCertPem
	}
	return nil
}

func (x *SupervisorMiddlewareService) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *SupervisorMiddlewareService) GetAllowInsecureTransport() bool {
	if x != nil {
		return x.AllowInsecureTransport
	}
	return false
}

var File_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_proto_rawDesc = "" +
	"\n" +
	"\rsandbox.proto\x12\x14openshell.sandbox.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x0fdatamodel.proto\"\xa8\x05\n" +
	"\rSandboxPolicy\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12F\n" +
	"\n" +
	"filesystem\x18\x02 \x01(\v2&.openshell.sandbox.v1.FilesystemPolicyR\n" +
	"filesystem\x12@\n" +
	"\blandlock\x18\x03 \x01(\v2$.openshell.sandbox.v1.LandlockPolicyR\blandlock\x12=\n" +
	"\aprocess\x18\x04 \x01(\v2#.openshell.sandbox.v1.ProcessPolicyR\aprocess\x12c\n" +
	"\x10network_policies\x18\x05 \x03(\v28.openshell.sandbox.v1.SandboxPolicy.NetworkPoliciesEntryR\x0fnetworkPolicies\x12l\n" +
	"\x13network_middlewares\x18\x06 \x03(\v2;.openshell.sandbox.v1.SandboxPolicy.NetworkMiddlewaresEntryR\x12networkMiddlewares\x1ak\n" +
	"\x14NetworkPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12=\n" +
	"\x05value\x18\x02 \x01(\v2'.openshell.sandbox.v1.NetworkPolicyRuleR\x05value:\x028\x01\x1at\n" +
	"\x17NetworkMiddlewaresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.openshell.sandbox.v1.NetworkMiddlewareConfigR\x05value:\x028\x01\"w\n" +
	"\x10FilesystemPolicy\x12'\n" +
	"\x0finclude_workdir\x18\x01 \x01(\bR\x0eincludeWorkdir\x12\x1b\n" +
	"\tread_only\x18\x02 \x03(\tR\breadOnly\x12\x1d\n" +
	"\n" +
	"read_write\x18\x03 \x03(\tR\treadWrite\"6\n" +
	"\x0eLandlockPolicy\x12$\n" +
	"\rcompatibility\x18\x01 \x01(\tR\rcompatibility\"Q\n" +
	"\rProcessPolicy\x12\x1e\n" +
	"\vrun_as_user\x18\x01 \x01(\tR\trunAsUser\x12 \n" +
	"\frun_as_group\x18\x02 \x01(\tR\n" +
	"runAsGroup\"\xad\x01\n" +
	"\x11NetworkPolicyRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12C\n" +
	"\tendpoints\x18\x02 \x03(\v2%.openshell.sandbox.v1.NetworkEndpointR\tendpoints\x12?\n" +
	"\bbinaries\x18\x03 \x03(\v2#.openshell.sandbox.v1.NetworkBinaryR\bbinaries\"\xff\x01\n" +
	"\x17NetworkMiddlewareConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"middleware\x18\x02 \x01(\tR\n" +
	"middleware\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x19\n" +
	"\bon_error\x18\x04 \x01(\tR\aonError\x12N\n" +
	"\tendpoints\x18\x05 \x01(\v20.openshell.sandbox.v1.MiddlewareEndpointSelectorR\tendpoints\x12\x14\n" +
	"\x05order\x18\x06 \x01(\x05R\x05order\"P\n" +
	"\x1aMiddlewareEndpointSelector\x12\x18\n" +
	"\ainclude\x18\x01 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x02 \x03(\tR\aexclude\"6\n" +
	"\x18NetworkCredentialBinding\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"\xdb\v\n" +
	"\x0fNetworkEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x126\n" +
	"\x03tls\x18\x04 \x01(\x0e2$.openshell.sandbox.v1.NetworkTlsModeR\x03tls\x12N\n" +
	"\venforcement\x18\x05 \x01(\x0e2,.openshell.sandbox.v1.NetworkEnforcementModeR\venforcement\x12A\n" +
	"\x06access\x18\x06 \x01(\x0e2).openshell.sandbox.v1.NetworkAccessPresetR\x06access\x122\n" +
	"\x05rules\x18\a \x03(\v2\x1c.openshell.sandbox.v1.L7RuleR\x05rules\x12\x1f\n" +
	"\vallowed_ips\x18\b \x03(\tR\n" +
	"allowedIps\x12\x14\n" +
	"\x05ports\x18\t \x03(\rR\x05ports\x12?\n" +
	"\n" +
	"deny_rules\x18\n" +
	" \x03(\v2 .openshell.sandbox.v1.L7DenyRuleR\tdenyRules\x12.\n" +
	"\x13allow_encoded_slash\x18\v \x01(\bR\x11allowEncodedSlash\x12+\n" +
	"\x11persisted_queries\x18\f \x01(\tR\x10persistedQueries\x12~\n" +
	"\x19graphql_persisted_queries\x18\r \x03(\v2B.openshell.sandbox.v1.NetworkEndpoint.GraphqlPersistedQueriesEntryR\x17graphqlPersistedQueries\x123\n" +
	"\x16graphql_max_body_bytes\x18\x0e \x01(\rR\x13graphqlMaxBodyBytes\x12\x12\n" +
	"\x04path\x18\x0f \x01(\tR\x04path\x12@\n" +
	"\x1cwebsocket_credential_rewrite\x18\x10 \x01(\bR\x1awebsocketCredentialRewrite\x12E\n" +
	"\x1frequest_body_credential_rewrite\x18\x11 \x01(\bR\x1crequestBodyCredentialRewrite\x12)\n" +
	"\x10advisor_proposed\x18\x12 \x01(\bR\x0fadvisorProposed\x12-\n" +
	"\x12credential_signing\x18\x13 \x01(\tR\x11credentialSigning\x12'\n" +
	"\x0fsigning_service\x18\x14 \x01(\tR\x0esigningService\x12%\n" +
	"\x0esigning_region\x18\x15 \x01(\tR\rsigningRegion\x124\n" +
	"\x17json_rpc_max_body_bytes\x18\x16 \x01(\rR\x13jsonRpcMaxBodyBytes\x122\n" +
	"\x03mcp\x18\x17 \x01(\v2 .openshell.sandbox.v1.McpOptionsR\x03mcp\x12]\n" +
	"\x12credential_binding\x18\x18 \x01(\v2..openshell.sandbox.v1.NetworkCredentialBindingR\x11credentialBinding\x12B\n" +
	"\x1dallow_uninspected_credentials\x18\x19 \x01(\bR\x1ballowUninspectedCredentials\x123\n" +
	"\x15provider_credentialed\x18\x1a \x01(\bR\x14providerCredentialed\x1ar\n" +
	"\x1cGraphqlPersistedQueriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.openshell.sandbox.v1.GraphqlOperationR\x05value:\x028\x01\"\xd2\x01\n" +
	"\n" +
	"McpOptions\x12/\n" +
	"\x11strict_tool_names\x18\x01 \x01(\bH\x00R\x0fstrictToolNames\x88\x01\x01\x12A\n" +
	"\x1ballow_all_known_mcp_methods\x18\x02 \x01(\bH\x01R\x17allowAllKnownMcpMethods\x88\x01\x01\x12\x1a\n" +
	"\bversions\x18\x03 \x03(\tR\bversionsB\x14\n" +
	"\x12_strict_tool_namesB\x1e\n" +
	"\x1c_allow_all_known_mcp_methods\"x\n" +
	"\x10GraphqlOperation\x12%\n" +
	"\x0eoperation_type\x18\x01 \x01(\tR\roperationType\x12%\n" +
	"\x0eoperation_name\x18\x02 \x01(\tR\roperationName\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\"\x88\x04\n" +
	"\n" +
	"L7DenyRule\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12A\n" +
	"\x05query\x18\x04 \x03(\v2+.openshell.sandbox.v1.L7DenyRule.QueryEntryR\x05query\x12%\n" +
	"\x0eoperation_type\x18\x05 \x01(\tR\roperationType\x12%\n" +
	"\x0eoperation_name\x18\x06 \x01(\tR\roperationName\x12\x16\n" +
	"\x06fields\x18\a \x03(\tR\x06fields\x12D\n" +
	"\x06params\x18\t \x03(\v2,.openshell.sandbox.v1.L7DenyRule.ParamsEntryR\x06params\x1a^\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.openshell.sandbox.v1.L7QueryMatcherR\x05value:\x028\x01\x1a_\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.openshell.sandbox.v1.L7QueryMatcherR\x05value:\x028\x01J\x04\b\b\x10\t\"=\n" +
	"\x06L7Rule\x123\n" +
	"\x05allow\x18\x01 \x01(\v2\x1d.openshell.sandbox.v1.L7AllowR\x05allow\"\xff\x03\n" +
	"\aL7Allow\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12>\n" +
	"\x05query\x18\x04 \x03(\v2(.openshell.sandbox.v1.L7Allow.QueryEntryR\x05query\x12%\n" +
	"\x0eoperation_type\x18\x05 \x01(\tR\roperationType\x12%\n" +
	"\x0eoperation_name\x18\x06 \x01(\tR\roperationName\x12\x16\n" +
	"\x06fields\x18\a \x03(\tR\x06fields\x12A\n" +
	"\x06params\x18\t \x03(\v2).openshell.sandbox.v1.L7Allow.ParamsEntryR\x06params\x1a^\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.openshell.sandbox.v1.L7QueryMatcherR\x05value:\x028\x01\x1a_\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.openshell.sandbox.v1.L7QueryMatcherR\x05value:\x028\x01J\x04\b\b\x10\t\"6\n" +
	"\x0eL7QueryMatcher\x12\x12\n" +
	"\x04glob\x18\x01 \x01(\tR\x04glob\x12\x10\n" +
	"\x03any\x18\x02 \x03(\tR\x03any\"2\n" +
	"\rNetworkBinary\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04pathJ\x04\b\x02\x10\x03R\aharness\"\x81\x01\n" +
	"\x17GetSandboxConfigRequest\x12R\n" +
	"\x0fworkspace_scope\x18\x03 \x01(\v2).openshell.datamodel.v1.WorkspaceSelectorR\x0eworkspaceScope\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x19\n" +
	"\x17GetGatewayConfigRequest\"\x82\x02\n" +
	"\x18GetGatewayConfigResponse\x12X\n" +
	"\bsettings\x18\x01 \x03(\v2<.openshell.sandbox.v1.GetGatewayConfigResponse.SettingsEntryR\bsettings\x12+\n" +
	"\x11settings_revision\x18\x02 \x01(\x04R\x10settingsRevision\x1a_\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".openshell.sandbox.v1.SettingValueR\x05value:\x028\x01\"\x9f\x01\n" +
	"\fSettingValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vbytes_value\x18\x04 \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"\x86\x01\n" +
	"\x10EffectiveSetting\x128\n" +
	"\x05value\x18\x01 \x01(\v2\".openshell.sandbox.v1.SettingValueR\x05value\x128\n" +
	"\x05scope\x18\x02 \x01(\x0e2\".openshell.sandbox.v1.SettingScopeR\x05scope\"\xb1\b\n" +
	"\x18GetSandboxConfigResponse\x12;\n" +
	"\x06policy\x18\x01 \x01(\v2#.openshell.sandbox.v1.SandboxPolicyR\x06policy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x1f\n" +
	"\vpolicy_hash\x18\x03 \x01(\tR\n" +
	"policyHash\x12X\n" +
	"\bsettings\x18\x04 \x03(\v2<.openshell.sandbox.v1.GetSandboxConfigResponse.SettingsEntryR\bsettings\x12'\n" +
	"\x0fconfig_revision\x18\x05 \x01(\x04R\x0econfigRevision\x12G\n" +
	"\rpolicy_source\x18\x06 \x01(\x0e2\".openshell.sandbox.v1.PolicySourceR\fpolicySource\x122\n" +
	"\x15global_policy_version\x18\a \x01(\rR\x13globalPolicyVersion\x122\n" +
	"\x15provider_env_revision\x18\b \x01(\x04R\x13providerEnvRevision\x12w\n" +
	"\x1esupervisor_middleware_services\x18\t \x03(\v21.openshell.sandbox.v1.SupervisorMiddlewareServiceR\x1csupervisorMiddlewareServices\x12\x1c\n" +
	"\tworkspace\x18\n" +
	" \x01(\tR\tworkspace\x12C\n" +
	"\x1epolicy_validation_failure_mode\x18\v \x01(\tR\x1bpolicyValidationFailureMode\x12H\n" +
	" extension_authentication_enabled\x18\f \x01(\bR\x1eextensionAuthenticationEnabled\x12:\n" +
	"\x19provider_attachment_epoch\x18\x0e \x01(\tR\x17providerAttachmentEpoch\x125\n" +
	"\x16configuration_admitted\x18\r \x01(\bR\x15configurationAdmitted\x12/\n" +
	"\x13configuration_error\x18\x10 \x01(\tR\x12configurationError\x12:\n" +
	"\x19configuration_instance_id\x18\x0f \x01(\tR\x17configurationInstanceId\x1ac\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.openshell.sandbox.v1.EffectiveSettingR\x05value:\x028\x01\"\xd2\x02\n" +
	"\x1bSupervisorMiddlewareService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rgrpc_endpoint\x18\x02 \x01(\tR\fgrpcEndpoint\x12*\n" +
	"\x11max_payload_bytes\x18\x03 \x01(\x04R\x0fmaxPayloadBytes\x12B\n" +
	"\x0frequest_timeout\x18h \x01(\v2\x19.google.protobuf.DurationR\x0erequestTimeout\x12%\n" +
	"\x0ftls_ca_cert_pem\x18\x05 \x01(\fR\ftlsCaCertPem\x12\x1a\n" +
	"\baudience\x18\x06 \x01(\tR\baudience\x128\n" +
	"\x18allow_insecure_transport\x18\a \x01(\bR\x16allowInsecureTransportJ\x04\b\x04\x10\x05R\atimeout*\x97\x01\n" +
	"\x0eNetworkTlsMode\x12 \n" +
	"\x1cNETWORK_TLS_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15NETWORK_TLS_MODE_SKIP\x10\x01\x12\"\n" +
	"\x1aNETWORK_TLS_MODE_TERMINATE\x10\x02\x1a\x02\b\x01\x12$\n" +
	"\x1cNETWORK_TLS_MODE_PASSTHROUGH\x10\x03\x1a\x02\b\x01*\x8c\x01\n" +
	"\x16NetworkEnforcementMode\x12(\n" +
	"$NETWORK_ENFORCEMENT_MODE_UNSPECIFIED\x10\x00\x12$\n" +
	" NETWORK_ENFORCEMENT_MODE_ENFORCE\x10\x01\x12\"\n" +
	"\x1eNETWORK_ENFORCEMENT_MODE_AUDIT\x10\x02*\xa7\x01\n" +
	"\x13NetworkAccessPreset\x12%\n" +
	"!NETWORK_ACCESS_PRESET_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fNETWORK_ACCESS_PRESET_READ_ONLY\x10\x01\x12$\n" +
	" NETWORK_ACCESS_PRESET_READ_WRITE\x10\x02\x12\x1e\n" +
	"\x1aNETWORK_ACCESS_PRESET_FULL\x10\x03*b\n" +
	"\fSettingScope\x12\x1d\n" +
	"\x19SETTING_SCOPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SETTING_SCOPE_SANDBOX\x10\x01\x12\x18\n" +
	"\x14SETTING_SCOPE_GLOBAL\x10\x02*b\n" +
	"\fPolicySource\x12\x1d\n" +
	"\x19POLICY_SOURCE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15POLICY_SOURCE_SANDBOX\x10\x01\x12\x18\n" +
	"\x14POLICY_SOURCE_GLOBAL\x10\x02B<Z:github.com/IniZio/nexus/internal/openshell/computedriverpbb\x06proto3"

var (
	file_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_proto_rawDescData []byte
)

func file_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)))
	})
	return file_sandbox_proto_rawDescData
}

var file_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_sandbox_proto_goTypes = []any{
	(NetworkTlsMode)(0),                 // 0: openshell.sandbox.v1.NetworkTlsMode
	(NetworkEnforcementMode)(0),         // 1: openshell.sandbox.v1.NetworkEnforcementMode
	(NetworkAccessPreset)(0),            // 2: openshell.sandbox.v1.NetworkAccessPreset
	(SettingScope)(0),                   // 3: openshell.sandbox.v1.SettingScope
	(PolicySource)(0),                   // 4: openshell.sandbox.v1.PolicySource
	(*SandboxPolicy)(nil),               // 5: openshell.sandbox.v1.SandboxPolicy
	(*FilesystemPolicy)(nil),            // 6: openshell.sandbox.v1.FilesystemPolicy
	(*LandlockPolicy)(nil),              // 7: openshell.sandbox.v1.LandlockPolicy
	(*ProcessPolicy)(nil),               // 8: openshell.sandbox.v1.ProcessPolicy
	(*NetworkPolicyRule)(nil),           // 9: openshell.sandbox.v1.NetworkPolicyRule
	(*NetworkMiddlewareConfig)(nil),     // 10: openshell.sandbox.v1.NetworkMiddlewareConfig
	(*MiddlewareEndpointSelector)(nil),  // 11: openshell.sandbox.v1.MiddlewareEndpointSelector
	(*NetworkCredentialBinding)(nil),    // 12: openshell.sandbox.v1.NetworkCredentialBinding
	(*NetworkEndpoint)(nil),             // 13: openshell.sandbox.v1.NetworkEndpoint
	(*McpOptions)(nil),                  // 14: openshell.sandbox.v1.McpOptions
	(*GraphqlOperation)(nil),            // 15: openshell.sandbox.v1.GraphqlOperation
	(*L7DenyRule)(nil),                  // 16: openshell.sandbox.v1.L7DenyRule
	(*L7Rule)(nil),                      // 17: openshell.sandbox.v1.L7Rule
	(*L7Allow)(nil),                     // 18: openshell.sandbox.v1.L7Allow
	(*L7QueryMatcher)(nil),              // 19: openshell.sandbox.v1.L7QueryMatcher
	(*NetworkBinary)(nil),               // 20: openshell.sandbox.v1.NetworkBinary
	(*GetSandboxConfigRequest)(nil),     // 21: openshell.sandbox.v1.GetSandboxConfigRequest
	(*GetGatewayConfigRequest)(nil),     // 22: openshell.sandbox.v1.GetGatewayConfigRequest
	(*GetGatewayConfigResponse)(nil),    // 23: openshell.sandbox.v1.GetGatewayConfigResponse
	(*SettingValue)(nil),                // 24: openshell.sandbox.v1.SettingValue
	(*EffectiveSetting)(nil),            // 25: openshell.sandbox.v1.EffectiveSetting
	(*GetSandboxConfigResponse)(nil),    // 26: openshell.sandbox.v1.GetSandboxConfigResponse
	(*SupervisorMiddlewareService)(nil), // 27: openshell.sandbox.v1.SupervisorMiddlewareService
	nil,                                 // 28: openshell.sandbox.v1.SandboxPolicy.NetworkPoliciesEntry
	nil,                                 // 29: openshell.sandbox.v1.SandboxPolicy.NetworkMiddlewaresEntry
	nil,                                 // 30: openshell.sandbox.v1.NetworkEndpoint.GraphqlPersistedQueriesEntry
	nil,                                 // 31: openshell.sandbox.v1.L7DenyRule.QueryEntry
	nil,                                 // 32: openshell.sandbox.v1.L7DenyRule.ParamsEntry
	nil,                                 // 33: openshell.sandbox.v1.L7Allow.QueryEntry
	nil,                                 // 34: openshell.sandbox.v1.L7Allow.ParamsEntry
	nil,                                 // 35: openshell.sandbox.v1.GetGatewayConfigResponse.SettingsEntry
	nil,                                 // 36: openshell.sandbox.v1.GetSandboxConfigResponse.SettingsEntry
	(*structpb.Struct)(nil),             // 37: google.protobuf.Struct
	(*WorkspaceSelector)(nil),           // 38: openshell.datamodel.v1.WorkspaceSelector
	(*durationpb.Duration)(nil),         // 39: google.protobuf.Duration
}
var file_sandbox_proto_depIdxs = []int32{
	6,  // 0: openshell.sandbox.v1.SandboxPolicy.filesystem:type_name -> openshell.sandbox.v1.FilesystemPolicy
	7,  // 1: openshell.sandbox.v1.SandboxPolicy.landlock:type_name -> openshell.sandbox.v1.LandlockPolicy
	8,  // 2: openshell.sandbox.v1.SandboxPolicy.process:type_name -> openshell.sandbox.v1.ProcessPolicy
	28, // 3: openshell.sandbox.v1.SandboxPolicy.network_policies:type_name -> openshell.sandbox.v1.SandboxPolicy.NetworkPoliciesEntry
	29, // 4: openshell.sandbox.v1.SandboxPolicy.network_middlewares:type_name -> openshell.sandbox.v1.SandboxPolicy.NetworkMiddlewaresEntry
	13, // 5: openshell.sandbox.v1.NetworkPolicyRule.endpoints:type_name -> openshell.sandbox.v1.NetworkEndpoint
	20, // 6: openshell.sandbox.v1.NetworkPolicyRule.binaries:type_name -> openshell.sandbox.v1.NetworkBinary
	37, // 7: openshell.sandbox.v1.NetworkMiddlewareConfig.config:type_name -> google.protobuf.Struct
	11, // 8: openshell.sandbox.v1.NetworkMiddlewareConfig.endpoints:type_name -> openshell.sandbox.v1.MiddlewareEndpointSelector
	0,  // 9: openshell.sandbox.v1.NetworkEndpoint.tls:type_name -> openshell.sandbox.v1.NetworkTlsMode
	1,  // 10: openshell.sandbox.v1.NetworkEndpoint.enforcement:type_name -> openshell.sandbox.v1.NetworkEnforcementMode
	2,  // 11: openshell.sandbox.v1.NetworkEndpoint.access:type_name -> openshell.sandbox.v1.NetworkAccessPreset
	17, // 12: openshell.sandbox.v1.NetworkEndpoint.rules:type_name -> openshell.sandbox.v1.L7Rule
	16, // 13: openshell.sandbox.v1.NetworkEndpoint.deny_rules:type_name -> openshell.sandbox.v1.L7DenyRule
	30, // 14: openshell.sandbox.v1.NetworkEndpoint.graphql_persisted_queries:type_name -> openshell.sandbox.v1.NetworkEndpoint.GraphqlPersistedQueriesEntry
	14, // 15: openshell.sandbox.v1.NetworkEndpoint.mcp:type_name -> openshell.sandbox.v1.McpOptions
	12, // 16: openshell.sandbox.v1.NetworkEndpoint.credential_binding:type_name -> openshell.sandbox.v1.NetworkCredentialBinding
	31, // 17: openshell.sandbox.v1.L7DenyRule.query:type_name -> openshell.sandbox.v1.L7DenyRule.QueryEntry
	32, // 18: openshell.sandbox.v1.L7DenyRule.params:type_name -> openshell.sandbox.v1.L7DenyRule.ParamsEntry
	18, // 19: openshell.sandbox.v1.L7Rule.allow:type_name -> openshell.sandbox.v1.L7Allow
	33, // 20: openshell.sandbox.v1.L7Allow.query:type_name -> openshell.sandbox.v1.L7Allow.QueryEntry
	34, // 21: openshell.sandbox.v1.L7Allow.params:type_name -> openshell.sandbox.v1.L7Allow.ParamsEntry
	38, // 22: openshell.sandbox.v1.GetSandboxConfigRequest.workspace_scope:type_name -> openshell.datamodel.v1.WorkspaceSelector
	35, // 23: openshell.sandbox.v1.GetGatewayConfigResponse.settings:type_name -> openshell.sandbox.v1.GetGatewayConfigResponse.SettingsEntry
	24, // 24: openshell.sandbox.v1.EffectiveSetting.value:type_name -> openshell.sandbox.v1.SettingValue
	3,  // 25: openshell.sandbox.v1.EffectiveSetting.scope:type_name -> openshell.sandbox.v1.SettingScope
	5,  // 26: openshell.sandbox.v1.GetSandboxConfigResponse.policy:type_name -> openshell.sandbox.v1.SandboxPolicy
	36, // 27: openshell.sandbox.v1.GetSandboxConfigResponse.settings:type_name -> openshell.sandbox.v1.GetSandboxConfigResponse.SettingsEntry
	4,  // 28: openshell.sandbox.v1.GetSandboxConfigResponse.policy_source:type_name -> openshell.sandbox.v1.PolicySource
	27, // 29: openshell.sandbox.v1.GetSandboxConfigResponse.supervisor_middleware_services:type_name -> openshell.sandbox.v1.SupervisorMiddlewareService
	39, // 30: openshell.sandbox.v1.SupervisorMiddlewareService.request_timeout:type_name -> google.protobuf.Duration
	9,  // 31: openshell.sandbox.v1.SandboxPolicy.NetworkPoliciesEntry.value:type_name -> openshell.sandbox.v1.NetworkPolicyRule
	10, // 32: openshell.sandbox.v1.SandboxPolicy.NetworkMiddlewaresEntry.value:type_name -> openshell.sandbox.v1.NetworkMiddlewareConfig
	15, // 33: openshell.sandbox.v1.NetworkEndpoint.GraphqlPersistedQueriesEntry.value:type_name -> openshell.sandbox.v1.GraphqlOperation
	19, // 34: openshell.sandbox.v1.L7DenyRule.QueryEntry.value:type_name -> openshell.sandbox.v1.L7QueryMatcher
	19, // 35: openshell.sandbox.v1.L7DenyRule.ParamsEntry.value:type_name -> openshell.sandbox.v1.L7QueryMatcher
	19, // 36: openshell.sandbox.v1.L7Allow.QueryEntry.value:type_name -> openshell.sandbox.v1.L7QueryMatcher
	19, // 37: openshell.sandbox.v1.L7Allow.ParamsEntry.value:type_name -> openshell.sandbox.v1.L7QueryMatcher
	24, // 38: openshell.sandbox.v1.GetGatewayConfigResponse.SettingsEntry.value:type_name -> openshell.sandbox.v1.SettingValue
	25, // 39: openshell.sandbox.v1.GetSandboxConfigResponse.SettingsEntry.value:type_name -> openshell.sandbox.v1.EffectiveSetting
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_sandbox_proto_init() }
func file_sandbox_proto_init() {
	if File_sandbox_proto != nil {
		return
	}
	file_datamodel_proto_init()
	file_sandbox_proto_msgTypes[9].OneofWrappers = []any{}
	file_sandbox_proto_msgTypes[19].OneofWrappers = []any{
		(*SettingValue_StringValue)(nil),
		(*SettingValue_BoolValue)(nil),
		(*SettingValue_IntValue)(nil),
		(*SettingValue_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_proto_depIdxs,
		EnumInfos:         file_sandbox_proto_enumTypes,
		MessageInfos:      file_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_proto = out.File
	file_sandbox_proto_goTypes = nil
	file_sandbox_proto_depIdxs = nil
}
